create table if not exists patrol_firmware_version (
    firmware_id         varchar(64)  not null comment '固件ID',
    tenant_id           varchar(20)  default '000000' comment '租户编号',
    device_type         varchar(32)  not null comment '设备类型：HEADSET/GLASSES',
    vendor              varchar(64)  default null comment '厂商',
    chipset             varchar(64)  default null comment '芯片平台：ACTS/JL',
    device_model        varchar(100) default null comment '设备型号',
    hardware_version    varchar(64)  default null comment '硬件版本',
    firmware_type       varchar(32)  default 'FULL' comment '固件类型',
    version_code        int          not null comment '排序版本号',
    version_name        varchar(64)  not null comment '固件版本名称',
    min_current_version varchar(64)  default null comment '最低可升级当前版本',
    max_current_version varchar(64)  default null comment '最高可升级当前版本',
    force_update        tinyint(1)   default 0 comment '是否强制升级',
    changelog           text         default null comment '更新日志',
    download_url        varchar(500) default null comment '下载地址',
    sha256              varchar(128) default null comment '固件包SHA-256',
    file_id             varchar(64)  default null comment '关联文件ID',
    file_size_bytes     bigint       default 0 comment '文件大小',
    package_format      varchar(32)  default null comment '包格式：bin/zip/ufw',
    upgrade_mode        varchar(32)  default 'APP_BLE' comment '升级模式',
    gray_scope          varchar(32)  default 'ALL' comment '灰度范围',
    gray_targets        text         default null comment '灰度目标',
    status              varchar(32)  not null comment '状态',
    published_at        datetime     default null comment '发布时间',
    remark              varchar(500) default null comment '备注',
    create_dept         bigint(20)   default null comment '创建部门',
    create_by           bigint(20)   default null comment '创建者',
    create_time         datetime     default null comment '创建时间',
    update_by           bigint(20)   default null comment '更新者',
    update_time         datetime     default null comment '更新时间',
    del_flag            char(1)      default '0' comment '删除标志',
    primary key (firmware_id),
    key idx_patrol_firmware_match (tenant_id, status, device_type, chipset, version_code),
    key idx_patrol_firmware_file (file_id)
) engine=innodb default charset=utf8mb4 comment='设备固件版本表';

create table if not exists patrol_firmware_upgrade_task (
    task_id       varchar(64)  not null comment '升级任务ID',
    tenant_id     varchar(20)  default '000000' comment '租户编号',
    device_id     varchar(64)  not null comment '设备ID',
    firmware_id   varchar(64)  not null comment '固件ID',
    operator_id   varchar(64)  default null comment '操作人',
    from_version  varchar(64)  default null comment '原固件版本',
    to_version    varchar(64)  default null comment '目标固件版本',
    status        varchar(32)  not null comment '状态',
    progress      decimal(6,3) default 0 comment '进度',
    error_code    varchar(64)  default null comment '错误码',
    error_message varchar(500) default null comment '错误信息',
    started_at    datetime     default null comment '开始时间',
    finished_at   datetime     default null comment '完成时间',
    create_dept   bigint(20)   default null comment '创建部门',
    create_by     bigint(20)   default null comment '创建者',
    create_time   datetime     default null comment '创建时间',
    update_by     bigint(20)   default null comment '更新者',
    update_time   datetime     default null comment '更新时间',
    del_flag      char(1)      default '0' comment '删除标志',
    primary key (task_id),
    key idx_patrol_firmware_task_device (tenant_id, device_id, started_at),
    key idx_patrol_firmware_task_status (tenant_id, status)
) engine=innodb default charset=utf8mb4 comment='设备固件升级任务表';
